/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> HeschDevBoard
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 30.05.2017 14:02:34
* Description       -> Characters for 7 Segment Display
*
*
*
*/

#ifndef __FONT_H__
#define __FONT_H__


#include <avr/io.h>

/* 7 segment char table */
char charMap [][2] =
{
	{ '0' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C | LED_SEGMENT_D | LED_SEGMENT_E | LED_SEGMENT_F					},
	{ '1' , LED_SEGMENT_B | LED_SEGMENT_C																					},
	{ '2' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D									},
	{ '3' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_C | LED_SEGMENT_D									},
	{ '4' , LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_B | LED_SEGMENT_C													},
	{ '5' ,	LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_C | LED_SEGMENT_D									},
	{ '6' ,	LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D | LED_SEGMENT_C					},
	{ '7' ,	LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C																	},
	{ '8' ,	LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C | LED_SEGMENT_D | LED_SEGMENT_E | LED_SEGMENT_F | LED_SEGMENT_G	},
	{ '9' ,	LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_C | LED_SEGMENT_D					},
	{ '.' , LED_SEGMENT_DP																									},
	{ ' ' , 0x00																											},
	{ '-' , LED_SEGMENT_G																									},
	{ '°' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_B													},
	{ '`' , LED_SEGMENT_A																									},
	{ '´' , LED_SEGMENT_D																									},
	{ '-' , LED_SEGMENT_G																									},
	{ 'A' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_C					},
	{ 'a' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_C					},
	{ 'B' , LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_C | LED_SEGMENT_D									},
	{ 'b' , LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_C | LED_SEGMENT_D									},
	{ 'C' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_D													},
	{ 'c' , LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D																	},
	{ 'D' , LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D | LED_SEGMENT_C									},
	{ 'd' , LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D | LED_SEGMENT_C									},
	{ 'E' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D									},
	{ 'e' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D									},
	{ 'F' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_G													},
	{ 'f' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_G													},
	{ 'L' , LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_D																	},
	{ 'l' , LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_D																	},	
	{ 'H' , LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_C | LED_SEGMENT_B | LED_SEGMENT_G									},
	{ 'h' , LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_C | LED_SEGMENT_B | LED_SEGMENT_G									},
	{ 'O' , LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_C | LED_SEGMENT_D													},
	{ 'o' , LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_C | LED_SEGMENT_D													},
	{ 'V' , LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_D | LED_SEGMENT_C | LED_SEGMENT_B									},
	{ 'v' , LED_SEGMENT_F | LED_SEGMENT_E | LED_SEGMENT_D | LED_SEGMENT_C | LED_SEGMENT_B									},
	{ 'R' , LED_SEGMENT_E | LED_SEGMENT_G																					},
	{ 'r' , LED_SEGMENT_E | LED_SEGMENT_G																					},
	{ 'P' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_E									},
	{ 'p' , LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_E									},
	{ 'J' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C | LED_SEGMENT_D | LED_SEGMENT_E									},
	{ 'j' , LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C | LED_SEGMENT_D | LED_SEGMENT_E									},
	{ ':' , LED_SEGMENT_F | LED_SEGMENT_E																					},
	{ '\0'																													}, // End of Table
};

char segments [][2] = 
{
	{ '0' , LED_SEGMENT_A	},
	{ '1' , LED_SEGMENT_B	},
	{ '2' , LED_SEGMENT_C	},
	{ '3' , LED_SEGMENT_D	},
	{ '4' , LED_SEGMENT_E	},
	{ '5' , LED_SEGMENT_F	},
	{ '6' , LED_SEGMENT_G	},
	{ '7' , LED_SEGMENT_DP	},
	{ ' ' , 0x00			},
	{ '\0'					}, // End of Table	
};

#endif