/* Generated by CodeDescriptor 1.0.0.0 */
/*
* Project Name      -> HeschDevBoard
* Version           -> 1.0
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 30.05.2017 14:02:34
* Description       -> Characters for 7 Segment Display
*
*
*
*/

#ifndef FONT_H
#define FONT_H


#include <avr/io.h>
#include "hard_def.h"

/* 7 segment char table */
const unsigned char ascii[17] =
{
	(LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C | LED_SEGMENT_D | LED_SEGMENT_E | LED_SEGMENT_F					),// 0
	(LED_SEGMENT_B | LED_SEGMENT_C																					),// 1
	(LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D									),// 2
	(LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_G | LED_SEGMENT_C | LED_SEGMENT_D									),// 3
	(LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_B | LED_SEGMENT_C													),// 4
	(LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_C | LED_SEGMENT_D									),// 5
	(LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D | LED_SEGMENT_C					),// 6
	(LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C																	),// 7
	(LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_C | LED_SEGMENT_D | LED_SEGMENT_E | LED_SEGMENT_F | LED_SEGMENT_G	),// 8
	(LED_SEGMENT_A | LED_SEGMENT_B | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_C | LED_SEGMENT_D					),// 9
	(LED_SEGMENT_DP																									),// dp
	(0x00																											),// all off
	(LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_B													),// °C
	(LED_SEGMENT_A																									),// sense 1
	(LED_SEGMENT_D																									),// sense 2
	(LED_SEGMENT_G																									),// -
	(LED_SEGMENT_G | LED_SEGMENT_D																					),// .- 
};

const unsigned char Character[2] =
{
	(LED_SEGMENT_A | LED_SEGMENT_F | LED_SEGMENT_G | LED_SEGMENT_E | LED_SEGMENT_D), //E
	(LED_SEGMENT_G | LED_SEGMENT_E												  ), //r
};


#endif