/* Generated by Header_Generator V1.0 */ 

/*
* Project Name -> Kalibrierumschaltbaugruppe Kombi 2017
* Version      -> 1.0
* Author       -> Hm
* Build Date   -> 21.04.2017
* Description  -> Hardware defines			  
*/	

#include "hard_def.h"

void hardware_init(void)
{
	/* gpios as output */
	DDR(GLCD_PORT) 	 			|= ((1<<GLCD_CS1_bp) | (1<<GLCD_RES_bp) | (1<<GLCD_A0_bp) | (1<<GLCD_SCL_bp) | (1<<GLCD_DATA_bp));
	DDR(GLCD_LED_PORT) 			|= ((1<<GLCD_LED_BLUE_bp) | (1<<GLCD_LED_GREEN_bp) | (1<<GLCD_LED_RED_bp));
	DDR(LED_HEARTBEAT_PORT) 	|= ( 1<<LED_HEARTBEAT_bp);
	DDR(VIBRATION_MOTOR_PORT)	|= ( 1<<VIBRATION_MOTOR_bp);
	DDR(SOUND_PORT)				|= ( 1<<SOUND_bp);
	DDR(RELAIS_PORT1_PORT)		|= ((RELAIS_1_PORT1) | (RELAIS_2_PORT1) | (RELAIS_3_PORT1) | (RELAIS_4_PORT1) | (RELAIS_5_PORT1) | (RELAIS_6_PORT1));
	DDR(RELAIS_PORT2_PORT)		|= ((RELAIS_7_PORT2) | (RELAIS_8_PORT2));

	SOUND_DDR |= (1<<SOUND_bp);
	
	/* gpios as input */
	DDR(SWITCH_PORT)			&= ~((1<<SWITCH_ENTER_bp) | (1<<SWITCH_UP_bp) | (1<<SWITCH_DOWN_bp) | (1<<SWITCH_RETURN_bp));
	DDR(MEASURE_VCC_PORT) 		&= ~( 1<<MEASURE_VCC_bp);
	DDR(ENC_SWITCH_PORT)  		&= ~( 1<<ENC_SWITCH_bp);
	DDR(ENC_PORT)		 		&= ~((1<<ENC_A) | (1<<ENC_B));
}