/* Generated by CodeDescriptor 1.5.0.0907 */
/*
* Project Name      -> stringHandler
* Version           -> 1.0.0.0920
* Author            -> Hm @ Workstadion.: QP-01-02
* Build Date        -> 20.09.2017 07:50:01
* Description       -> Description
*
*
*
*/

#ifndef STRINGHANDLER_H
#define STRINGHANDLER_H

#include <avr/io.h>

#define ALLOWED_COMMANDS	30

typedef struct{
	char *allow[ALLOWED_COMMANDS];
	char detected;
}cmd_t;

typedef char (*searchCmdPtr)(char cmdBuff[], cmd_t *cmds);
char searchCmd(char cmdBuff[], cmd_t *cmds);

typedef uint8_t (*compareStringPtr)(char *strOne, char *strTwo);
uint8_t compareString(char *strOne, char *strTwo);

typedef uint8_t (*countStringPtr)(char *str);
uint8_t countString(char *str);


typedef struct{
	
	compareStringPtr	Compare;
	countStringPtr		Count;
	searchCmdPtr		Search;
	
}string_t;

extern string_t str;
extern cmd_t cmd;

#endif