/* Generated by Header_Generator V1.0 */

/*
* Project Name -> Kalibrierumschaltbaugruppe Kombi 2017
* Version      -> 1.0
* Author       -> Hm
* Build Date   -> 28.04.2017
* Description  -> Project Strings
*/

#include <avr/io.h>

#include "build_info.h"

#ifndef __STRINGS_H__
#define __STRINGS_H__

enum
{
	ID_PROJECT,
	ID_HARDWARE_DATE,
	ID_MADE_BY,
	ID_OK,
	ID_ERR,
	ID_CRC_ERR,
	ID_PSWD_ACCEPTED,
	ID_PSWD_WRONG,
	
	ID_MENUE_SYS_TIME,
	ID_MENUE_SYS_DATE,
	ID_MENUE_FREE_ROW,
	ID_MENUE_RELAIS_NAME,

	ID_MENUE_RELAIS_NAME_1,
	ID_MENUE_RELAIS_NAME_2,
	ID_MENUE_RELAIS_NAME_3,
	ID_MENUE_RELAIS_NAME_4,
	ID_MENUE_RELAIS_NAME_5,
	ID_MENUE_RELAIS_NAME_6,
	ID_MENUE_RELAIS_NAME_7,
	ID_MENUE_RELAIS_NAME_8,
	
	ID_MENUE_ENTER_EXIT,
	ID_MENUE_BRIGHTNESS,
	ID_MENUE_CONTRAST,
	ID_MENUE_SERNR,
	ID_MENUE_ADMIN_MODE,
	ID_MENUE_PASSWORD,
	ID_MENUE_RELAIS,
	ID_MENUE_TEMPERATURE,
	
	ID_MENUE_APP_INFO,
	ID_MENUE_MAC_ADDR,
	
	ID_MENUE_RESTART_APP,
	ID_MENUE_ACTIVE_RELAIS,
	ID_MENUE_ADMIN_LOGGED_IN,
	ID_MENUE_WRONG_PASSWORD,
	ID_MENUE_USER_ADMIN,
	ID_MENUE_USER_WORKER,
	ID_MENUE_NOT_CONNECTED,
	ID_MENUE_CONNECTED,
	ID_MENUE_MASTER,
	ID_MENUE_SLAVE,
	ID_MENUE_BLTH_STATE,
	ID_MENUE_USER,
	ID_MENUE_UNKNOWN_CMD,
	ID_MENUE_PASSWORD_CHARS,
	
	ID_CNT	
};

typedef struct  
{
	char *id[ID_CNT];
	
	char *(*buildSwVer)(void);
}DevBoard_t;

const DevBoard_t __flash board =
{
	{
		[ID_PROJECT			] =	"DevBoard GLCD",
		[ID_HARDWARE_DATE	] = "HD.:18.04.17",
		[ID_MADE_BY			] = "by J.H Elec(C)",
		
		[ID_OK				] = "ok",
		[ID_ERR				] = "fail",
		[ID_CRC_ERR			] = "crc fail\r\n",
		[ID_PSWD_ACCEPTED	] = "pswd ok!",	
		
		[ID_MENUE_TEMPERATURE] = "Temperatur",
		
		[ID_PSWD_WRONG		] = "pswd wrong!",
		[ID_MENUE_FREE_ROW	] = "                                                                         ",
		[ID_MENUE_APP_INFO	] = "App. Info",
		[ID_MENUE_BRIGHTNESS] = "Helligkeit",
		[ID_MENUE_CONTRAST	] = "Kontrast",
		[ID_MENUE_SERNR		] = "SerNr.",
		[ID_MENUE_ADMIN_MODE] = "Admin. Mode",
		[ID_MENUE_RELAIS	] = "Relais",
		[ID_MENUE_PASSWORD	] = "Passwort",
		[ID_MENUE_SYS_TIME	] = "Uhrzeit",
		[ID_MENUE_SYS_DATE	] = "Datum",
		[ID_MENUE_MAC_ADDR	] = "MAC Adr.",	
		
		[ID_MENUE_ADMIN_LOGGED_IN	] = "Admin. ok!",
		[ID_MENUE_ENTER_EXIT		] = "Enter zum Verlassen!",
		[ID_MENUE_ACTIVE_RELAIS		] = "Aktive Relais.: ",
		[ID_MENUE_RESTART_APP		] = "Reboot..",
		[ID_MENUE_RELAIS_NAME_1		] = " 1 ",
		[ID_MENUE_RELAIS_NAME_2		] = " 2 ",
		[ID_MENUE_RELAIS_NAME_3		] = " 3 ",
		[ID_MENUE_RELAIS_NAME_4		] = " 4 ",
		[ID_MENUE_RELAIS_NAME_5		] = " 5 ",
		[ID_MENUE_RELAIS_NAME_6		] = " 6 ",
		[ID_MENUE_RELAIS_NAME_7		] = " 7 ",
		[ID_MENUE_RELAIS_NAME_8		] = " 8 ",
		[ID_PSWD_WRONG				] = "pswd wrong!",
		[ID_MENUE_USER_ADMIN		] = "Administrator",
		[ID_MENUE_USER_WORKER		] = "Werker",
		[ID_MENUE_USER				] = "User.:",
		[ID_MENUE_NOT_CONNECTED		] = "nicht verbunden..",
		[ID_MENUE_CONNECTED			] = "Verbunden..",
		[ID_MENUE_MASTER			] = "Master.:",
		[ID_MENUE_SLAVE				] = "Slave.:",
		[ID_MENUE_BLTH_STATE		] = "Status",
		[ID_MENUE_UNKNOWN_CMD		] = "Kommando Fehler!",	
		[ID_MENUE_PASSWORD_CHARS	] = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	},
	
	.buildSwVer = buildVer,
};

#endif
