/* Generated by Header_Generator V1.0 */ 

/*
* Project Name -> Kalibrierumschaltbaugruppe Kombi 2017
* Version      -> 1.0
* Author       -> Hm
* Build Date   -> 21.04.2017
* Description  -> Hardware Configuration			  
*/	

#ifndef HARD_INIT_H
#define HARD_INIT_H



/*	Configure µC
*	@para 	-> none
*	@return -> none
*/
void hardware_init(void);

#endif